- name: Configure Network Devices
  hosts: routers
  gather_facts: no
  tasks:
    - name: Change hostname
      cisco.ios.ios_config:
        lines:
          - hostname Router1

    - name: Configure Interface
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet0/1
          - ip address 192.168.1.10 255.255.255.0
          - no shutdown

    - name: Save Configuration
      cisco.ios.ios_config:
        save_when: always
